### ISSUE TITLE
EditorUI is not defined

### ISSUE THREAD

**Issue by MadcapJake** [fireball-x/editor-framework#136]
Error messages in Chrome Dev Tools console:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:29 Uncaught ReferenceError: EditorUI is not defined
index.html:26 Uncaught ReferenceError: EditorUI is not defined
    (anonymous function) @ index.html:26
    Evented.trigger @ pace.js:190
    (anonymous function) @ pace.js:899
```
I installed editor-framework via `generator-editor-framework`.  Interestingly, when I click on `Developer -> UI Preview -> ui-kit`, it loads the ui elements just fine, but the main window is just a blank white fill.

Not sure if this is a generator problem or internal to editor-framework

**Comment by jwu** [comment]
HI @MadcapJake , thank you for your report. I found the problem is caused by out of the date of the generator. I've update it to date in this commit: https://github.com/fireball-x/generator-editor-framework/commit/972cee056e20fcd98ef1f418c422130524c95ed2.

Just pull the generator, and re-generate the editor-framework app and run it again.

Any problem let me known.
