### ISSUE TITLE
Feature: add projectPath to the field of editor-framework?

### ISSUE THREAD

**Issue by yorkie** [fireball-x/editor-framework#55]
`projectPath` should also be defined and documented here just like `appHome` and `appPath`, right? Just met a problem when I was using `Editor.url` stuffs with code-editor.

/cc @jwu

**Comment by yorkie** [comment]
I saw we defined the `projectPath` at [this line](https://github.com/fireball-x/fireball/blob/master/canvas-studio/init.js#L14).

**Comment by jwu** [comment]
Currently the `Editor` namespace shared in Canvas-Studio and Editor-Framework. So it might confuse developer for those variables. Basically I should add api document in Canvas Studio for Editor.projectPath.

I think the projectPath doesn't belong to `editor-framework`. This is because in `editor-framework` we didn't have features about project. The project is quite different for each App, and I still don't find too much common case to abstract it. Once we support project abstraction in `editor-framework`, I will think about this.

**Comment by jwu** [comment]
BTW: what it is your problem when you use `Editor.url` without `projectPath` defined(documented)?

**Comment by yorkie** [comment]
Ok, I will close this because of your description about is clear now, and my problem is I thought the `projectPath` should be under the `editor-framework`, never mind.
